### ISSUE TITLE
Normal inventory doesn't exist and survival is broken.

### ISSUE THREAD

**Issue by Esat1604** [CrisXolt/Project-4JD-UI#1]
You are probably working on survival inventory right now but still, I want to document this bug. In this version, survival is completely broken. It shows the creative inventory but it's all messed up. I suggest making a button on the bottom right of the screen to change the menu between survival and creative.

**Comment by CrisXolt** [comment]
Hello, I have solved this and now it should only appear the inventory in survival mode, but it should still take time to open, but it is only once.

And yeah, thanks for testing it! ;D
