### ISSUE TITLE
is there a way to access the addons/resource packs screen with the pack enabled

### ISSUE THREAD

**Issue by gayfieri** [CrisXolt/Project-4JD-UI#10]
i dont know if this is a dumb question or not

**Comment by Shahil6570** [comment]
There is, first go to Help & Options > Options > Game > Resource Packs
Picture:
![Capture](https://user-images.githubusercontent.com/68023400/181073900-6bfc2ba9-22aa-4fd1-9e98-86f3d5ff6003.PNG)

**Comment by gayfieri** [comment]
tysm
