### ISSUE TITLE
Creative Menu is broken

### ISSUE THREAD

**Issue by Denissffd** [CrisXolt/Project-4JD-UI#29]
this happen when trying to open inventory in creative mode
![image](https://user-images.githubusercontent.com/91484520/185371600-80f80faa-7760-4f69-b65a-673114b55100.png)

**Comment by Bellypoop12345612** [comment]
> this happen when trying to open inventory in creative mode ![image](https://user-images.githubusercontent.com/91484520/185371600-80f80faa-7760-4f69-b65a-673114b55100.png)

same it happens to me

**Comment by T-Sean2** [comment]
> this happen when trying to open inventory in creative mode ![image](https://user-images.githubusercontent.com/91484520/185371600-80f80faa-7760-4f69-b65a-673114b55100.png)

Same here also

**Comment by Bellypoop12345612** [comment]
> > this happen when trying to open inventory in creative mode ![image](https://user-images.githubusercontent.com/91484520/185371600-80f80faa-7760-4f69-b65a-673114b55100.png)
> 
> Same here also

Why hasn't the crafting menu been implemented yet?

**Comment by CrisXolt** [comment]
Hello everyone, I haven't implemented the new version about creative UI remake yet. I decided to delete for those who want to experience the UI only in survival without lag when opening. At the moment I'm creating the "adapted" mode for the creative UI, which would not be much accurate about UI design, but great for performance, after this, the more accurate UI design "museum" mode will also be implemented, be patient, ok? Thanks for testing it anyway! ;D

**Comment by CrisXolt** [comment]
> > > this happen when trying to open inventory in creative mode ![image](https://user-images.githubusercontent.com/91484520/185371600-80f80faa-7760-4f69-b65a-673114b55100.png)
> > 
> > 
> > Same here also
> 
> Why hasn't the crafting menu been implemented yet?

Hello everyone, I haven't implemented the new version about creative UI remake yet. I decided to delete for those who want to experience the UI only in survival without lag when opening. At the moment I'm creating the "adaptive" mode for the creative UI, which would not be much accurate about UI design, but great for performance, after this, the more accurate UI design "museum" mode will also be implemented, be patient, ok? Thanks for testing it anyway! ;D

**Comment by monkey1270** [comment]
l

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Denissffd** [comment]
thanks
