### ISSUE TITLE
Can't close inventory in Museum UI Classic

### ISSUE THREAD

**Issue by Ruby101-was-taken** [CrisXolt/Project-4JD-UI#36]
Unable to close the inventory when using the Museum UI Classic subpack, either using the inventory button or Escape key
![image](https://user-images.githubusercontent.com/80523483/189491776-aaaf50fd-5e84-48a7-a21e-d64ccd1caa34.png)

**Comment by Whfww** [comment]
This is an issue he will fix Later You can you The old VDX project ui in commits
