### ISSUE TITLE
I can't download the pack

### ISSUE THREAD

**Issue by Tktyt13** [CrisXolt/Project-4JD-UI#37]
You can give a google drive link or mediafire is more easier

**Comment by Whfww** [comment]
> You can give a google drive link or mediafire is more easier

Desktop site press download press download.zip

**Comment by CrisXolt** [comment]
Just click "Code" and then press "Download ZIP", after downloading "Project-4JD-UI-master.zip", rename .zip to .mcpack. That's all.
