### ISSUE TITLE
Screens don’t match console edition and on xbox1 the logo just disappears 

### ISSUE THREAD

**Issue by Whfww** [CrisXolt/Project-4JD-UI#41]
![IMG_6148](https://user-images.githubusercontent.com/112290993/194727754-60c3f18f-2042-4cd0-9291-f44a129337fb.png)
![IMG_6149](https://user-images.githubusercontent.com/112290993/194727755-74e0c823-87c5-481a-98f6-a7b98423f578.png)
![IMG_6151](https://user-images.githubusercontent.com/112290993/194727758-4df18239-aafd-41eb-8c26-019891bc5d58.png)
![IMG_6152](https://user-images.githubusercontent.com/112290993/194727765-c8bf3310-3eef-4904-919e-2e74ee82fdb2.png)

**Comment by CrisXolt** [comment]
Unfortunately I have made the decision to only put the title "Bedrock Edition" for the entire platform and it will not be reverted.

**Comment by Whfww** [comment]
There’s no hide hand option option in the user interface

**Comment by CrisXolt** [comment]
> There’s no hide hand option option in the user interface

Don't worry, I've already solved it, just wait for me to git commit.
![Minecraft 09_10_2022 04_30_55 p  m](https://user-images.githubusercontent.com/13043319/194785235-5679d22c-7428-45f6-ae88-2d9417eb3e71.png)
