### ISSUE TITLE
The chest is completely invisible

### ISSUE THREAD

**Issue by THN3** [CrisXolt/Project-4JD-UI#43]
Even the ender chest and the trapped chest are all missing.

**Comment by THN3** [comment]
https://user-images.githubusercontent.com/113951444/195408464-9cfbceab-1a57-4ec8-99d9-ebd77d73cbbf.MOV

**Comment by CrisXolt** [comment]
![Minecraft 12_10_2022 11_39_35 a  m](https://user-images.githubusercontent.com/13043319/195422224-81826770-8b80-447d-8f18-fa222cf8bd69.png)
There seems to be a compatibility issue with other resource packs. If you are using with Console Aspects and have this error, I will review it and resolve it.

**Comment by THN3** [comment]
Looks like it’s just a compatibility issue, when I took off the other texture packs
