### ISSUE TITLE
Creating New World Screen is not the old ui

### ISSUE THREAD

**Issue by VetarexTR** [CrisXolt/Project-4JD-UI#46]
i mean when you creating a new world in pc its using the new creating screen not the old ui

**Comment by Ruby101-was-taken** [comment]
Read the known issues

**Comment by Whfww** [comment]
BRO U CANT CHANGE THE NEW UI

**Comment by DR4GEND** [comment]
It's normal Minecraft to add a new world creation interface and unfortunately the code is protected and we can't change the properties so you have no choice.
