### ISSUE TITLE
Can Post Mcpedl Console ui 4JD And Added Mixed ui and Pvp like Java ui

### ISSUE THREAD

**Issue by MineFayyadh789** [CrisXolt/Project-4JD-UI#51]
Pls Post Mcpedl and Added Subpack Normal And Mixed Ui and PVP  Ui *A request To post Mcpedl And Added Mixed And Pvp *

**Comment by BestFurTH** [comment]
it not even finished yet

**Comment by MineFayyadh789** [comment]
Yeah I known I wonder he working Ui gui

**Comment by CrisXolt** [comment]
When I finish everything (including Museum Crafting UI Concept) I will publish the project on all pages, including MCPEDL.

**Comment by MineFayyadh789** [comment]
Yes Yes Thank you Crixolt

**Comment by MineFayyadh789** [comment]
And when you Update added Mixed And PvP 4JD Master in Mcpedl

**Comment by Whfww** [comment]
There’s no 1.8 GUI for console edition it would be a good idea for the classic textures since on the museum UI  mode the icons for the categories Are the new textures so it could be the old textures for the 1.8 GUI And same for the survival Mode categories
